### ISSUE TITLE
Dependencies (virtualenv)

### ISSUE THREAD

**Issue by D-ECHO** [slawekmikula/scripts-osm2city#2]
Hi there!

those are some very helpful tools, thank you so much.

Just a few remarks about the dependencies:
* imaging, lapack and blas don't seem to be available on my system, but also osm2city seems to run fine without them
* pyproj seems to need to be a version between 2.0 and 2.5 otherwise osm2city fails, so this might be something to add to the installation command ( ./bin/pip install -I pyproj==2.4 )
* descartes is needed for osm2city.py, but isn't included in the list, you might want to add it

Thanks again

**Comment by slawekmikula** [comment]
Thanks. I'll check it on my system and update it. I wasn't using osm2city for a long time so it might changed a bit. I'll forward upstream info about pyproj - I think it should be working without version limit. 

Thanks for the kind words also :)

**Comment by slawekmikula** [comment]
Regarding pyproj > 2.4 there is already issue reported: https://gitlab.com/osm2city/osm2city/-/issues/144

Everything else went to updated readme. Thanks. Closing.

**Comment by D-ECHO** [comment]
Thank you!
